backend:
  name: git-gateway
  branch: main
media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"
publish_mode: simple
local_backend: false

collections:
  - name: "site"
    label: "Site Content"
    delete: false
    editor:
      preview: false
    files:
      - label: "Main Site Settings"
        name: "settings"
        file: "content/site.json"
        format: json
        fields:
          - { label: "Site Name", name: "siteName", widget: "string" }
          # Navigation labels
          - label: "Navigation Labels"
            name: "nav"
            widget: "object"
            fields:
              - { label: "Home", name: "homeLabel", widget: "string", default: "Home", required: false }
              - { label: "About", name: "aboutLabel", widget: "string", default: "About", required: false }
              - { label: "Events", name: "eventsLabel", widget: "string", default: "Events", required: false }
              - { label: "Gallery", name: "galleryLabel", widget: "string", default: "Gallery", required: false }
              - { label: "Membership", name: "membershipLabel", widget: "string", default: "Membership", required: false }
              - { label: "Spotlight", name: "spotlightLabel", widget: "string", default: "Spotlight", required: false }
              - { label: "Members", name: "membersLabel", widget: "string", default: "Members", required: false }
              - { label: "Contact", name: "contactLabel", widget: "string", default: "Contact", required: false }
          - { label: "Hero Title Line 1", name: "heroLine1", widget: "string" }
          - { label: "Hero Title Line 2", name: "heroLine2", widget: "string" }
          - { label: "Hero Paragraph", name: "heroParagraph", widget: "text", required: false }
          - { label: "Featured Tagline", name: "featuredTagline", widget: "text", required: false }
          # Featured quilts (use these three slots to avoid list editing bug)
          - label: "Featured Quilt 1"
            name: "featured1"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
          - label: "Featured Quilt 2"
            name: "featured2"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
          - label: "Featured Quilt 3"
            name: "featured3"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
          - label: "Featured Quilts"
            name: "featuredImages"
            widget: "list"
            summary: "{{fields.caption}}"
            hint: "Add as many featured quilts as you like. Reorder to change display order."
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Caption (optional)", name: "caption", widget: "string", required: false }
          - { label: "Spotlight Bio", name: "spotlightBio", widget: "text", required: false }
          - { label: "Spotlight Image", name: "spotlightImage", widget: "image", required: false }
          - { label: "Contact Email", name: "contactEmail", widget: "string", required: false }
          - { label: "Meeting Line", name: "meetingLine", widget: "string", required: false }

  - name: "events"
    label: "Events"
    editor:
      preview: false
    files:
      - label: "Events List"
        name: "events"
        file: "content/events.json"
        format: json
        fields:
          - label: "Events"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "string", hint: "e.g., Third Wednesday, 7:00 PM" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "resources"
    label: "Member Resources"
    editor:
      preview: false
    files:
      - label: "Resources List"
        name: "resources"
        file: "content/resources.json"
        format: json
        fields:
          - label: "Resources"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string", hint: "Link to file or page" }

  - name: "newsletters"
    label: "Newsletters"
    editor:
      preview: false
    files:
      - label: "Newsletters"
        name: "newsletters"
        file: "content/newsletters.json"
        format: json
        fields:
          - label: "Newsletters"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "string", hint: "YYYY-MM or Month YYYY" }
              - { label: "URL", name: "url", widget: "string" }

  - name: "member_sections"
    label: "Members: Sections (Tabs)"
    editor:
      preview: false
    files:
      - label: "Member Sections"
        name: "member_sections"
        file: "content/member_sections.json"
        format: json
        fields:
          - label: "Sections"
            name: "sections"
            widget: "list"
            summary: "{{fields.title}}"
            hint: "Add tabs like Patterns, Charity, Show & Tell. Reorder to change tab order."
            fields:
              - { label: "ID (no spaces)", name: "id", widget: "string", hint: "e.g., patterns, charity, show-tell" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
              - { label: "Allow Local Image Drop (preview only)", name: "allowLocalDrop", widget: "boolean", required: false, default: true }
              - label: "Images"
                name: "images"
                widget: "list"
                summary: "{{fields.caption}}"
                fields:
                  - { label: "Image", name: "src", widget: "image" }
                  - { label: "Caption", name: "caption", widget: "string", required: false }
              - label: "PDF Links"
                name: "pdfs"
                widget: "list"
                summary: "{{fields.title}}"
                hint: "Set URL to # to auto-generate PDF from images in this section (title words are used to match). Or upload/select a PDF file."
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "URL or Upload", name: "url", widget: "file", required: false }

  - name: "hospitality"
    label: "Hospitality & Dark Horse"
    editor:
      preview: false
    files:
      - label: "Hospitality Grid"
        name: "hospitality"
        file: "content/hospitality.json"
        format: json
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Months"
            name: "months"
            widget: "list"
            summary: "{{fields.label}}"
            fields:
              - { label: "Month Label", name: "label", widget: "string" }
              - label: "Entries"
                name: "items"
                widget: "list"
                hint: "Six lines per month; leave blank lines for empty slots."
                field: { label: "Line", name: "line", widget: "string", required: false }
