name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lychee:
    name: Check links with lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --no-progress
            --exclude-mail
            --include-fragments
            --timeout 20
            --retry-wait-time 2
            --scheme https
            --verbose
            ./README.md
            ./quilt/**/*.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: set to false to allow failures without failing the workflow
          # LY_CI: true

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
